name: Build executables

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_script: build:linux
            binary_name: tosu-ipc-emulator
            archive_name: tosu-ipc-emulator-linux-x64.tar.gz

          - os: windows-latest
            build_script: build:win
            binary_name: tosu-ipc-emulator.exe
            archive_name: tosu-ipc-emulator-win-x64.tar.gz
    
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    name: Build for ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7
      
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '26'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build executable
        run: |
          echo "Building for ${{ matrix.os }}"
          npm run ${{ matrix.build_script }}

      - name: Archive Executable
        run: |
          cd dist
          
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "../${{ matrix.archive_name }}" "${{ matrix.binary_name }}"
          else
            tar -czvf "../${{ matrix.archive_name }}" "${{ matrix.binary_name }}"
          fi

      - name: Upload Release asset
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ matrix.archive_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
